sudo: required

language: node_js
node_js:
- lts/*

services:
  - docker

before install:
- npm install 
- docker build -t timelogingserver

script:
- docker run -it  timelogingserver  npm test 
- curl http://localhost:3030.


deploy:
  deploy:
  provider: gae
  keyfile: api-key.jon
  project: TimeLoggingServer
  on:
    branch: master