sudo: required

language: node_js
node_js:
- lts/*

services:
  - docker

script:
- docker build -t timelogingserver .
- docker run -it  timelogingserver  npm test 
- curl http://localhost:3030.

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master

deploy:
  deploy:
  provider: gae
  keyfile: api-key.json
  project: TimeLoggingServer
  on:
    branch: master