sudo: required

language: node_js
node_js:
- lts/*

services:
  - docker

before install:
- npm install  
- docker build -t timelogingserver .


deploy:
  provider: cloudfoundry
  username: stein_korsveien@msn.com
  password: DavidBowie1!
  api: https://api.run.pivotal.io
  organization: stein
  space: development
  on:
    branch: master