sudo: required

language: minimal

services:
  - docker

script:
- docker build -t steinko/timelogingserver .
- docker run  -p 3030:3030 -it  steinko/timelogingserver  npm test 
##- curl http://localhost:3030.

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master

##deploy:
 ## deploy:
 ## provider: gae
  ##keyfile: api-key.json
  ##project: TimeLoggingServer
 ##on:
  ##  branch: master