install:
- docker pull steinko/timeloggingserver

deploy:
  provider: cloudfoundry
  username: stein_korsveien@msn.com
  password: DavidBowie1!
  api: https://api.run.pivotal.io
  organization: stein
  space: development
  on:
    branch: master